#!/bin/sh
PATH=/etc/taxiboxx:$PATH
export PATH

[ -f /mnt/flashdrive/.not.mounted ] && exit 1
if [ ! -f /tmp/.swcheck ]; then
    touch /tmp/.swcheck
    exit 0
fi
FWDIR=/mnt/flashdrive/sw
mkdir -p $FWDIR
CV=$(cat /etc/taxiboxx/.VERSION)
SV=$(cat /mnt/flashdrive/sw/sw.ver)
if [ "$CV" = "" ]; then CV=0; fi
if [ "$SV" = "" ]; then SV=0; fi
cd $FWDIR

URL="$(uci -q get taxiboxx.webservice.url)/inst/version_sw.php"

. /usr/share/libubox/jshn.sh

RSLT=$(curl -L -k -s "${URL}")
json_load "$RSLT"
json_get_var VER status

if [ "$VER" = "" ]; then VER=0; fi
if [ $VER -gt $CV -a $VER -gt $SV ]; then
    rm *
    URL="$(uci -q get taxiboxx.webservice.url)/inst/sw"
    wget -q --no-check-certificate "$URL/sw.tar.gz" && \
    wget -q --no-check-certificate "$URL/sw.md5" && \
    wget -q --no-check-certificate "$URL/sw.ver"
fi
