#!/bin/sh
PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH

echo "Cache-Control: no-cache, no-store, must-revalidate"
echo "Pragma: no-cache"
echo "Expires: 0"
echo "Content-type: text/html"
echo ""

VFILE=/etc/taxiboxx/.VERSION
VER=$([ -f $VFILE ] && cat $VFILE)
[ "$VER" = "" ]&& VER=0
cat <<EOF
<html>
  <head>
    <title>Version</title>
  </head>
  <body>
    <h1>
      Version: $VER
    </h1>
  </body>
</html>
EOF

exit 0
