#!/bin/sh
PATH=/etc/taxiboxx:/usr/bin:/usr/sbin:/bin:/sbin
export PATH

echo "Cache-Control: no-cache, no-store, must-revalidate"
echo "Pragma: no-cache"
echo "Expires: 0"
echo "Content-type: text/html"
echo ""

MAC=$(cat /proc/net/arp | grep "^$REMOTE_ADDR "  | awk '{ print $4 }')
DMAC=$(cat /tmp/.driver)
GW_ID=$(getmac.sh)
ID=

if [ ! -z "$QUERY_STRING" ]; then
    ID=`echo "$QUERY_STRING" | sed -n 's/^.*id=\([^&]*\).*$/\1/p' | sed "s/%20/ /g" | sed "s/%3A/:/g"`
fi

if [ "$ID" != "" ]; then
    URL="/apks/${ID}.apk"
    cat <<EOF
<html>
  <head>
    <title>GetAd</title>
    <script type="text/javascript">
      location.href = "$URL";
    </script>
  </head>
  <body>
  </body>
</html>
EOF
fi

exit 0
